/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIView;

import BLL.Puntori;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Admin
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        getContentPane().setBackground(Color.WHITE);
    }
    
    public MainForm(Puntori p) {
        initComponents();
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   public MainForm(int userAutoriteti) {
        initComponents();
        
        setLocationRelativeTo(null);
        if(userAutoriteti!=1){
            kinemaButton.setVisible(false);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navMenu = new javax.swing.JDesktopPane();
        puntoretButton = new javax.swing.JButton();
        kinemaButton = new javax.swing.JButton();
        filmaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        ExitMI = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        CopyMI = new javax.swing.JMenuItem();
        PasteMI = new javax.swing.JMenuItem();
        DeleteMI = new javax.swing.JMenuItem();
        AdminMenu = new javax.swing.JMenu();
        PuntoretMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navMenu.setBackground(new java.awt.Color(255, 255, 255));

        puntoretButton.setText("Puntoret");
        puntoretButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoretButtonActionPerformed(evt);
            }
        });

        kinemaButton.setText("Kinema");
        kinemaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kinemaButtonActionPerformed(evt);
            }
        });

        filmaButton.setText("Filma");
        filmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmaButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Admin Panel");

        javax.swing.GroupLayout navMenuLayout = new javax.swing.GroupLayout(navMenu);
        navMenu.setLayout(navMenuLayout);
        navMenuLayout.setHorizontalGroup(
            navMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navMenuLayout.createSequentialGroup()
                .addGroup(navMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(navMenuLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(puntoretButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                        .addComponent(kinemaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(navMenuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(192, 192, 192)
                .addComponent(filmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        navMenuLayout.setVerticalGroup(
            navMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navMenuLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(navMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puntoretButton)
                    .addComponent(kinemaButton)
                    .addComponent(filmaButton))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        navMenu.setLayer(puntoretButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        navMenu.setLayer(kinemaButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        navMenu.setLayer(filmaButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        navMenu.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        FileMenu.setText("File");

        ExitMI.setText("Exit");
        FileMenu.add(ExitMI);

        jMenuBar1.add(FileMenu);

        EditMenu.setText("Edit");

        CopyMI.setText("Copy");
        CopyMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyMIActionPerformed(evt);
            }
        });
        EditMenu.add(CopyMI);

        PasteMI.setText("Paste");
        EditMenu.add(PasteMI);

        DeleteMI.setText("Delete");
        EditMenu.add(DeleteMI);

        jMenuBar1.add(EditMenu);

        AdminMenu.setText("Admin Options");

        PuntoretMI.setText("Puntoret");
        PuntoretMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntoretMIActionPerformed(evt);
            }
        });
        AdminMenu.add(PuntoretMI);

        jMenuBar1.add(AdminMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navMenu)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CopyMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CopyMIActionPerformed

    private void puntoretButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoretButtonActionPerformed
        PuntoriForm pf = new PuntoriForm();
        desktopPane.add(pf);
        pf.show();
    }//GEN-LAST:event_puntoretButtonActionPerformed

    private void PuntoretMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntoretMIActionPerformed
        PuntoriForm pf = new PuntoriForm();
        desktopPane.add(pf);
        pf.show();
    }//GEN-LAST:event_PuntoretMIActionPerformed

    private void filmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmaButtonActionPerformed
       FilmaForm ff = new FilmaForm();
       desktopPane.add(ff);
       ff.show();
    }//GEN-LAST:event_filmaButtonActionPerformed

    private void kinemaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kinemaButtonActionPerformed
       KinemaForm kf = new KinemaForm();
       desktopPane.add(kf);
       kf.show();
    }//GEN-LAST:event_kinemaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AdminMenu;
    private javax.swing.JMenuItem CopyMI;
    private javax.swing.JMenuItem DeleteMI;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenuItem ExitMI;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem PasteMI;
    private javax.swing.JMenuItem PuntoretMI;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton filmaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton kinemaButton;
    private javax.swing.JDesktopPane navMenu;
    private javax.swing.JButton puntoretButton;
    // End of variables declaration//GEN-END:variables
}
