/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIView;

import BLL.Filmi;
import BLL.Puntori;
import BLL.Rezervimi;
import DAL.CFormException;
import DAL.FilmiRepository;
import DAL.RezervimiRepository;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class RezervimiForm extends javax.swing.JFrame {
    FilmiRepository fr = new FilmiRepository();
    List<Filmi> filmat;
    Puntori p;
    /**
     * Creates new form RezervimiForm
     */
    public RezervimiForm() {
        initComponents();
         setLocationRelativeTo(null);
    }

    public RezervimiForm(Puntori p) {
        initComponents();
        setLocationRelativeTo(null);
        if(p.getAutoriteti().equals("user")) {
            adminPanel.setVisible(false);
            
        }
        try {
            filmat = fr.findAll();
        }catch(CFormException cfe ) {
            cfe.printStackTrace();
        }
        setSpinner();
        this.p = p;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        inceptionAdd = new javax.swing.JLabel();
        pulpAdd = new javax.swing.JLabel();
        hatefulAdd = new javax.swing.JLabel();
        threeAdd = new javax.swing.JLabel();
        avengersAdd = new javax.swing.JLabel();
        jokerAdd = new javax.swing.JLabel();
        interAdd = new javax.swing.JLabel();
        gladiatorAdd = new javax.swing.JLabel();
        wallAdd = new javax.swing.JLabel();
        whiplashAdd = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        adminPanel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rezTable = new javax.swing.JTable();
        totaliField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        orderButton = new javax.swing.JButton();
        inceptionSpinner = new javax.swing.JSpinner();
        pulpSpinner = new javax.swing.JSpinner();
        hatefulSpinner = new javax.swing.JSpinner();
        avengersSpinner = new javax.swing.JSpinner();
        threeSpinner = new javax.swing.JSpinner();
        wallSpinner = new javax.swing.JSpinner();
        whiplashSpinner = new javax.swing.JSpinner();
        gladiatorSpinner = new javax.swing.JSpinner();
        interstellarSpinner = new javax.swing.JSpinner();
        jokerSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText(" ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Joker");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Inception");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Pulp Fiction");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("The Hateful Eight");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Avengers");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("300");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Interstellar");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Gladiator");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Whiplash");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("WALL-E");

        inceptionAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inceptionAdd.setText("ADD");
        inceptionAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inceptionAddMouseClicked(evt);
            }
        });

        pulpAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pulpAdd.setText("FOTO");
        pulpAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pulpAddMouseClicked(evt);
            }
        });

        hatefulAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hatefulAdd.setText("FOTO");
        hatefulAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hatefulAddMouseClicked(evt);
            }
        });

        threeAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        threeAdd.setText("FOTO");
        threeAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeAddMouseClicked(evt);
            }
        });

        avengersAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        avengersAdd.setText("FOTO");
        avengersAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avengersAddMouseClicked(evt);
            }
        });

        jokerAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jokerAdd.setText("FOTO");
        jokerAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jokerAddMouseClicked(evt);
            }
        });

        interAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        interAdd.setText("FOTO");
        interAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                interAddMouseClicked(evt);
            }
        });

        gladiatorAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gladiatorAdd.setText("FOTO");
        gladiatorAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gladiatorAddMouseClicked(evt);
            }
        });

        wallAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wallAdd.setText("FOTO");
        wallAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wallAddMouseClicked(evt);
            }
        });

        whiplashAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        whiplashAdd.setText("FOTO");
        whiplashAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                whiplashAddMouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setText("Miresevini ne CinemaBooking");

        adminPanel.setText("Admin Tools");
        adminPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPanelActionPerformed(evt);
            }
        });

        rezTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Filmi", "Sasia", "Cmimi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(rezTable);

        totaliField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totaliField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totaliField.setText("0.0");

        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        orderButton.setText("Order");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(totaliField)
                        .addGroup(desktopPaneLayout.createSequentialGroup()
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(orderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                            .addGap(340, 340, 340)
                            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jokerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(91, 91, 91))
                        .addGroup(desktopPaneLayout.createSequentialGroup()
                            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(desktopPaneLayout.createSequentialGroup()
                                        .addGap(331, 331, 331)
                                        .addComponent(jokerAdd))
                                    .addGroup(desktopPaneLayout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(adminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(desktopPaneLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)))
                            .addGap(87, 87, 87)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inceptionAdd)
                            .addComponent(inceptionSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)))
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addContainerGap())
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(pulpAdd)
                                    .addComponent(interAdd)
                                    .addGroup(desktopPaneLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(pulpSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(9, 9, 9)))
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(gladiatorAdd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(whiplashAdd, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)
                                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hatefulAdd)
                                    .addGroup(desktopPaneLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(hatefulSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(avengersAdd)
                                    .addGroup(desktopPaneLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(avengersSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7)))
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wallAdd)
                                    .addComponent(jLabel13))
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(desktopPaneLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(threeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(threeAdd)
                                        .addGroup(desktopPaneLayout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(5, 5, 5))))
                                .addGap(21, 21, 21))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(interstellarSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(gladiatorSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(whiplashSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(wallSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24)))
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(adminPanel)))
                        .addGap(118, 118, 118)
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inceptionAdd)
                            .addComponent(pulpAdd)
                            .addComponent(hatefulAdd)
                            .addComponent(threeAdd)
                            .addComponent(avengersAdd))
                        .addGap(15, 15, 15)
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inceptionSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulpSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hatefulSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avengersSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(threeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(interAdd)
                            .addComponent(gladiatorAdd)
                            .addComponent(wallAdd)
                            .addComponent(whiplashAdd))
                        .addGap(18, 18, 18)
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wallSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(whiplashSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gladiatorSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(interstellarSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addComponent(jokerAdd)
                                .addGap(18, 18, 18)
                                .addComponent(jokerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addComponent(totaliField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)))
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cancelButton)
                                .addComponent(orderButton))
                            .addComponent(jLabel2))
                        .addGap(125, 125, 125))))
        );
        desktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(inceptionAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(pulpAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(hatefulAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(threeAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(avengersAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jokerAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(interAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(gladiatorAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(wallAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(whiplashAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(adminPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(totaliField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(cancelButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(orderButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(inceptionSpinner, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(pulpSpinner, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(hatefulSpinner, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(avengersSpinner, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(threeSpinner, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(wallSpinner, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(whiplashSpinner, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(gladiatorSpinner, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(interstellarSpinner, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jokerSpinner, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPanelActionPerformed
        // TODO add your handling code here:
        new MainForm().setVisible(true);
    }//GEN-LAST:event_adminPanelActionPerformed

    private void inceptionAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inceptionAddMouseClicked
        // TODO add your handling code here:
        gjejFilmin(3,(int)inceptionSpinner.getValue());
    }//GEN-LAST:event_inceptionAddMouseClicked

    private void pulpAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pulpAddMouseClicked
        gjejFilmin(4,(int)pulpSpinner.getValue());
    }//GEN-LAST:event_pulpAddMouseClicked

    private void hatefulAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hatefulAddMouseClicked
       gjejFilmin(5,(int)hatefulSpinner.getValue());
    }//GEN-LAST:event_hatefulAddMouseClicked

    private void avengersAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avengersAddMouseClicked
        gjejFilmin(6,(int)avengersSpinner.getValue());
    }//GEN-LAST:event_avengersAddMouseClicked

    private void threeAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeAddMouseClicked
        gjejFilmin(7,(int)threeSpinner.getValue());
    }//GEN-LAST:event_threeAddMouseClicked

    private void jokerAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jokerAddMouseClicked
        gjejFilmin(1,(int)jokerSpinner.getValue());
    }//GEN-LAST:event_jokerAddMouseClicked

    private void interAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_interAddMouseClicked
       gjejFilmin(8,(int)interstellarSpinner.getValue());
    }//GEN-LAST:event_interAddMouseClicked

    private void gladiatorAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gladiatorAddMouseClicked
        gjejFilmin(9,(int)gladiatorSpinner.getValue());
    }//GEN-LAST:event_gladiatorAddMouseClicked

    private void whiplashAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whiplashAddMouseClicked
        gjejFilmin(10,(int)whiplashSpinner.getValue());
    }//GEN-LAST:event_whiplashAddMouseClicked

    private void wallAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wallAddMouseClicked
        gjejFilmin(11,(int)wallSpinner.getValue());
    }//GEN-LAST:event_wallAddMouseClicked
    private void clearTable() {
        DefaultTableModel dm = (DefaultTableModel) rezTable.getModel();
        dm.setRowCount(0);
        dm.setNumRows(20);
        revalidate();
    }
    
    
    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        clearTable();
        totaliField.setText("0.0");
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        try {
            RezervimiRepository rr = new RezervimiRepository();
            Rezervimi r = new Rezervimi();
            r.setCmimi(kalkuloTotalin());
            r.setKinema(p.getKinema());
            r.setPuntori(p);
            r.setUlsja("B12");
            rr.create(r);
            JOptionPane.showMessageDialog(this, "Rezervimi u shtua me sukses!");
            
            
            
        }catch(CFormException cfe) {
            cfe.printStackTrace();
            JOptionPane.showMessageDialog(this, "Rezervimi deshtoi");
        }
    }//GEN-LAST:event_orderButtonActionPerformed

    private void gjejFilmin(int id, int sasia) {
        Filmi filmi = null;
        for(Filmi f : filmat) {
            if(f.getFilmiId() == id) {
                filmi = f;
                break;
            }
        }
        if(filmi != null) {
            addToTable(filmi, sasia);
            kalkuloTotalin();
        }
    }
    
    private void addToTable(Filmi f, int sasia) {
        int rowNr = rezTable.getModel().getRowCount();
        
        for(int i=0;i<rowNr;i++){
            if(rezTable.getValueAt(i, 0)== null){
                if(exists(f, sasia)) {
                    return;
                }else {
                    rezTable.setValueAt(f, i, 0);
                    rezTable.setValueAt(sasia, i, 1);
                    rezTable.setValueAt(5.0, i, 2);
                    return;
                }
            }
        }
        
    }
    
    private boolean exists(Filmi f, int sasia) {
            int rowNr = rezTable.getModel().getRowCount();
            for(int i = 0;i<rowNr;i++) {
               if(rezTable.getValueAt(i, 0) != null) { 
                    Filmi test = (Filmi)rezTable.getValueAt(i, 0);
                    if(test.equals(f)) {
                        int currentSasia = (int) rezTable.getValueAt(i, 1);
                        System.out.println(currentSasia);
                        currentSasia = sasia;  
                        System.out.println(currentSasia);
                        rezTable.setValueAt(currentSasia, i, 1);
                        System.out.println(rezTable.getValueAt(i, 1));
                        return true;        
                    }
               }

            }
        return false;
    }
    
    public void setSpinner() {
        Component [] comp = desktopPane.getComponents();
        for(int i=0;i<comp.length;i++){
            if(comp[i] instanceof JSpinner){
            ((JSpinner)comp[i]).setValue(1);
            }
        }
    }
    
    private double kalkuloTotalin() {
        double totali = 0;
        int rowNr = rezTable.getModel().getRowCount();
        
        for(int i=0;i<rowNr;i++){
            if(rezTable.getValueAt(i, 0)!= null) {
               double cmimi = (double)rezTable.getValueAt(i, 2);
               int sasia = (int)rezTable.getValueAt(i, 1);
               double itemTotal = cmimi * sasia;
               totali += itemTotal;
            }
        }
        String s = String.valueOf(totali);
        totaliField.setText(s);
        return totali;
               
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RezervimiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RezervimiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RezervimiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RezervimiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RezervimiForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminPanel;
    private javax.swing.JLabel avengersAdd;
    private javax.swing.JSpinner avengersSpinner;
    private javax.swing.JButton cancelButton;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel gladiatorAdd;
    private javax.swing.JSpinner gladiatorSpinner;
    private javax.swing.JLabel hatefulAdd;
    private javax.swing.JSpinner hatefulSpinner;
    private javax.swing.JLabel inceptionAdd;
    private javax.swing.JSpinner inceptionSpinner;
    private javax.swing.JLabel interAdd;
    private javax.swing.JSpinner interstellarSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jokerAdd;
    private javax.swing.JSpinner jokerSpinner;
    private javax.swing.JButton orderButton;
    private javax.swing.JLabel pulpAdd;
    private javax.swing.JSpinner pulpSpinner;
    private javax.swing.JTable rezTable;
    private javax.swing.JLabel threeAdd;
    private javax.swing.JSpinner threeSpinner;
    private javax.swing.JTextField totaliField;
    private javax.swing.JLabel wallAdd;
    private javax.swing.JSpinner wallSpinner;
    private javax.swing.JLabel whiplashAdd;
    private javax.swing.JSpinner whiplashSpinner;
    // End of variables declaration//GEN-END:variables
}
